# Generated by Django 3.2.5 on 2022-11-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
