# Generated by Django 3.2.5 on 2022-11-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='drID',
            field=models.CharField(default='', max_length=20),
        ),
    ]
