# Generated by Django 3.2.5 on 2022-11-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0007_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.TextField(default='', max_length=100),
        ),
    ]
