# Generated by Django 3.2.5 on 2022-11-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0008_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('reqDoctor', models.CharField(max_length=100)),
                ('date_1', models.CharField(max_length=100)),
                ('date_2', models.CharField(max_length=100)),
                ('time_1', models.CharField(max_length=100)),
                ('time_2', models.CharField(max_length=100)),
                ('cconcern', models.TextField(max_length=1000)),
            ],
        ),
    ]
