# Generated by Django 3.2.5 on 2022-11-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0009_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
