# Generated by Django 3.2.5 on 2022-11-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0010_remove_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='cconcern',
            new_name='concern',
        ),
    ]
