# Generated by Django 3.2.5 on 2022-11-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0013_appointment_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptID', models.CharField(default='', max_length=100)),
                ('apptDate', models.CharField(max_length=100)),
                ('apptStatus', models.CharField(max_length=100)),
                ('userID', models.CharField(max_length=100)),
                ('reqDoctor', models.CharField(max_length=100)),
                ('concern', models.TextField(max_length=1000)),
                ('confirmDate', models.CharField(default='', max_length=100)),
                ('date1', models.CharField(default='', max_length=100)),
                ('date2', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
