# Generated by Django 3.2.5 on 2022-11-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0015_remove_appointmentadmin_concern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentadmin',
            name='userID',
        ),
        migrations.AddField(
            model_name='appointmentadmin',
            name='patientContact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointmentadmin',
            name='patientName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
