# Generated by Django 3.2.5 on 2022-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0016_auto_20221129_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmDate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
