# Generated by Django 3.2.5 on 2022-11-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0017_appointment_confirmdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentadmin',
            name='patientID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
