# Generated by Django 3.2.5 on 2022-11-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0018_appointmentadmin_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reqDoctor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
