# Generated by Django 3.2.5 on 2022-11-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0019_alter_appointment_reqdoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='concern',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='confirmDate',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
