# Generated by Django 3.2.5 on 2022-11-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCare_app', '0020_auto_20221130_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='imgurl',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
